# Generated by Django 6.0 on 2025-12-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('agency', 'Agency')], max_length=20),
        ),
    ]
