# Generated by Django 5.2.8 on 2025-11-29 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_post_photos_report_savedposts"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoostingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("premium", "Premium"),
                            ("gold", "Gold"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(
                        choices=[
                            ("individuals", "Individuals"),
                            ("agencies", "Agencies"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("credit_cost", models.FloatField(default=0.0)),
                ("duration", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Boosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.post"
                    ),
                ),
                (
                    "boost_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.boostingplan",
                    ),
                ),
            ],
        ),
    ]
