# Generated by Django 5.2.8 on 2026-01-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_phone_number_customuser_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="pics",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="profile_pic",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="main_pic",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="savedposts",
            unique_together={("user", "post")},
        ),
        migrations.DeleteModel(
            name="Photos",
        ),
    ]
