# Generated by Django 5.2.8 on 2025-12-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_customuser_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="buildingtype",
            new_name="building_type",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="listingtype",
            new_name="listing_type",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="titel",
            new_name="title",
        ),
        migrations.AlterField(
            model_name="post",
            name="latitude",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="longitude",
            field=models.FloatField(null=True),
        ),
    ]
