# Generated by Django 5.2.8 on 2025-12-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_rename_buildingtype_post_building_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="area",
            new_name="max_sqft",
        ),
        migrations.AddField(
            model_name="post",
            name="min_sqft",
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
