# Generated by Django 5.2.8 on 2025-12-02 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_rename_area_post_max_sqft_post_min_sqft"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="max_sqft",
            new_name="area",
        ),
        migrations.RemoveField(
            model_name="post",
            name="min_sqft",
        ),
    ]
