# Generated by Django 5.2.8 on 2025-12-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_max_sqft_post_area_remove_post_min_sqft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('agency', 'Agency')], default='normal', max_length=20),
        ),
    ]
