arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
preferred-supported-locales:
  - en
  - fr
  - ar
# Optional: path to write a list of untranslated messages
untranslated-messages-file: lib/l10n/untranslated_messages.txt
